---
# Create up challenge files directory on server. Customize this for your server's specific setup!
- name: Creating challenge destination directory
  file:
    dest: "{{ server_location }}"
    state: directory
    owner: root
    group: http
    mode: "0750"

# Create challenge files on server. Customize this for your server's specific setup!
- name: Copying challenge files for domains {{ ', '.join(domains) }}"
  copy:
    dest: "{{ server_location }}/{{ item.value[challenge].resource[('.well-known/acme-challenge/'|length):] }}"
    content: "{{ item.value[challenge].resource_value }}"
    owner: root
    group: http
    mode: "0640"
  with_dict: "{{ lets_encrypt_challenge.challenge_data }}"
