---
# Clean up challenge files on server. Customize this for your server's specific setup!
- name: "Cleaning up challenge files for domains {{ ', '.join(domains) }}"
  file:
    path: "{{ server_location }}/{{ item.value[challenge].resource[('.well-known/acme-challenge/'|length):] }}"
    state: absent
  with_dict: "{{ lets_encrypt_challenge.get('challenge_data', {}) }}"
