---
- name: "Cleaning up state and challenge files"
  local_action: file path=scratch/state-{{ domains[0] }}.json state=absent
  run_once: True

- name: "Cleaning up state and challenge files"
  local_action: file path=scratch/challenges-{{ domains[0] }} state=absent
  run_once: True
